### ISSUE TITLE
Last character disappears

### ISSUE THREAD

**Issue by karjac14** [konradjurk/ember-text-highlight#8]
Nice ember package here! 

I noticed that when typing, as it reaches the 2nd to the last character... the last (next) character disappears. It goes back though when you reach the very end.

I'll try to fix it and make a PR.

**Comment by konradjurk** [comment]
Thanks for submitting the bug! :) I'll fix this today.

**Comment by karjac14** [comment]
Wow thanks! I cloned the repo but Im getting a bower_components error when doing:

`yarn run test` or `ember serve`

error is : `Cannot find module '..../ember-text-highlight/bower_components/ember/ember-template-compiler'`

**Comment by konradjurk** [comment]
Added a test and fixed the bug with release 1.2.2 :)

Also, `ember serve` now actually exposes a little demo app.

To use it and run the tests, you currently need to `bower install ember` once before. Didn't document that as I'd like it to use yarn, but didn't succeed yet.
